Fix MIDI input on CoreMIDI
waddlesplash/QMidi pull request #33
Opened 2022-04-09 10:44 UTC by pvaibhav

The CoreMIDI input code was incorrect - it was only sending the first byte of the entire MIDI packet. Data sent by CoreMIDI is in a packet consisting of multiple MIDI messages. They must be broken up and sent individually to the listener.

2022-04-09 10:45 UTC, pvaibhav commented on src/OS/QMidi_CoreMidi.cpp
> -			emit(midiIn->midiEvent(*packet->data,
BUG: `*packet->data` is just dereferencing the first byte of the entire packet.

2022-04-09 12:59 UTC, waddlesplash requested changes

2022-04-09 12:59 UTC, waddlesplash commented on src/OS/QMidi_CoreMidi.cpp
> +		{
Brace to previous line.

2022-04-09 12:59 UTC, waddlesplash commented on src/OS/QMidi_CoreMidi.cpp
> +		if (byteCount != 0 && byteCount % 3 == 0)
Parens around `byteCount % 3`.

2022-04-09 12:59 UTC, waddlesplash commented on src/OS/QMidi_CoreMidi.cpp
> +				&& (packet->data[i] & 0x80) != 0x00)
whole if to one line, brace on same line.

2022-04-09 12:59 UTC, waddlesplash commented on src/OS/QMidi_CoreMidi.cpp
> +				// Make sure that it's a normal MIDI message. SysSex etc.
`SysEx`

2022-04-28 19:56 UTC, merged

2022-04-28 19:56 UTC, waddlesplash commented
Thanks!